version: '3.7'
services: 
  weather-sensor:
    image: 'weather-sensor:latest'
    container_name: 'weather-sensor'
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    devices:
      - /dev/mem:/dev/mem
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - /data/weather_sensor:/data
    restart: unless-stopped